apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    application: keycloak
  name: keycloak
spec:
  replicas: 1
  selector:
    deploymentConfig: keycloak
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        application: keycloak
        deploymentConfig: keycloak
      name: keycloak
    spec:
      containers:
        - env:
            - name: KC_HOSTNAME
              value: identity.b4mad.racing
            - name: KC_PROXY
              value: edge
            - name: KC_HOSTNAME_STRICT_BACKCHANNEL
              value: "true"
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  key: admin-username
                  name: keycloak
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: admin-password
                  name: keycloak
            - name: KC_DB
              value: postgres
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: database-user
                  name: postgresql
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: postgresql
            - name: KC_DB_URL_HOST
              value: postgresql
            - name: KC_DB_URL_DATABASE
              valueFrom:
                secretKeyRef:
                  key: database-name
                  name: postgresql
          image: quay.io/keycloak/keycloak:19.0.2
          livenessProbe:
            failureThreshold: 100
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
          name: keycloak
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            failureThreshold: 300
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
          resources:
            requests:
              cpu: "2"
              memory: 4Gi
            limits:
              cpu: "4"
              memory: 8Gi
          volumeMounts:
            - mountPath: /opt/keycloak/data
              name: keycloak-data
          args: ["start-dev"]
      volumes:
        - name: keycloak-data
          persistentVolumeClaim:
            claimName: keycloak-data
      serviceAccount: keycloak
      serviceAccountName: keycloak
