---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: postgres-metrics-exporter
  annotations:
    kubernetes.io/tls-acme: "true"
    haproxy.router.openshift.io/timeout: 45s
spec:
  to:
    kind: Service
    name: postgres-metrics-exporter
---
kind: Service
apiVersion: v1
metadata:
  name: postgres-metrics-exporter
spec:
  ports:
    - name: metrics
      protocol: TCP
      port: 80
      targetPort: 9187
  selector:
    service: postgres-metrics-exporter
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: postgres-metrics-exporter
spec:
  replicas: 1
  selector:
    service: postgres-metrics-exporter
  template:
    metadata:
      labels:
        service: postgres-metrics-exporter
    spec:
      containers:
        - name: "postgresql-metrics-exporter"
          image: wrouesnel/postgres_exporter
          env:
            - name: DATA_SOURCE_URI
              value: "pgbouncer:5432/keycloak?sslmode=disable"
            - name: DATA_SOURCE_USER
              valueFrom:
                secretKeyRef:
                  key: database-user
                  name: postgresql
            - name: DATA_SOURCE_PASS
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: postgresql
          ports:
            - containerPort: 9187
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /liveness
              port: 9187
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readiness
              port: 9187
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 5
            timeoutSeconds: 10
