kind: Service
apiVersion: v1
metadata:
  name: mosquitto-tcp
spec:
  externalTrafficPolicy: Cluster
  type: NodePort
  selector:
    app: mosquitto
  ports:
    - name: mosquitto-tcp
      nodePort: 31883
      port: 1883
      protocol: TCP
      targetPort: 1883