apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: paddock
spec:
  tags:
  - from:
      kind: DockerImage
      name: ghcr.io/b4mad/paddock:latest
    importPolicy:
      scheduled: true
    name: latest
    referencePolicy:
      type: Source
