kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: telemetry
  creationTimestamp: null
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  host: telemetry.b4mad.racing
  to:
    kind: Service
    name: b4mad-racing-influxdb2
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
