apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - service_account.yaml
configMapGenerator:
  - name: telegraf-config
    files:
      - telegraf.conf
generatorOptions:
  disableNameSuffixHash: true
