apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/grafana-v5
  - datasource-prometheus.yaml
  - dashboards/

generatorOptions:
  disableNameSuffixHash: true

patches:
  - target:
      kind: Ingress
      name: grafana
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: pitwall-nostromo-stage.b4mad.racing
      - op: replace
        path: /spec/tls/0/hosts/0
        value: pitwall-nostromo-stage.b4mad.racing
      - op: replace
        path: /spec/tls/0/secretName
        value: https-cert-pitwall-nostromo-stage.b4mad.racing

  - target:
      kind: GrafanaDatasource
      name: paddock
    patch: |-
      - op: replace
        path: /spec/datasource/url
        value: db-primary.b4mad-racing-stage.svc:5432
